nama = input("Nama                : ")
nim =  input("NIM                 : ")
par =  input("Kelas Paralel       : ")
ttl =  input("Tempat/Tanggal Lahir: ")
adr =  input("Alamat              : ")
hob =  input("Hobby               : ")
hp =   input("No. HP              : ")
print("")
print("Nama                :",nama)
print("NIM                 :",nim)
print("Kelas Paralel       :",par)
print("Tempat/Tanggal Lahir:",ttl)
print("Alamat              :",adr)
print("Hobby               :",hob)
print("No. HP              :",hp)